plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
  # https://github.com/facebook/create-react-app/issues/11793#issuecomment-998230832
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
